server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:bakerydb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  cors:
    allowed-origins: http://localhost:4200
  jwt:
    secret: "bakery-dev-secret-key-change-me-before-production-0123456789"
    expiration-ms: 86400000
